kind: Service
apiVersion: v1
metadata:
  name: fe-ui-public
  namespace: ui-service
spec:
  selector:
     run: fe-ui-public
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer