# build environment
FROM node:18 as builder
WORKDIR /app
COPY . .
COPY ./deploy/env-dev .env
# COPY ./deploy/vite.config.js-dev vite.config.js
RUN git config --global url."https://".insteadOf git://
RUN npm install
# RUN npm audit fix --force
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/deploy/config/nginx-default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
